[build]
  publish = "_site"
  command = "DEBUG=* eleventy"


[context.production.environment]
  NODE_VERSION = "12.16.1"

[context.branch-deploy.environment]
  NODE_VERSION = "12.16.1"

[context.deploy-preview.environment]
  NODE_VERSION = "12.16.1"
